#!/bin/bash

declare -A notas=(
    [1]="El archivo de configuración de un servicio DHCP es /etc/dhcp/dhcpd.conf"
    [2]="Los ficheros de registros de errores del sistema en Debian son /var/log/syslog"
    [3]="El número de puerto que usa el servicio DHCP es el 67"
    [4]="El fichero de configuración del servidor de Bind9 es /etc/bind/named.conf"
    [5]="El fichero de zonas de Bind9 es /etc/bind/named.conf.local"
    [6]="El fichero de zonas por defecto de Bind9 es /etc/bind/named.conf.default-zones"
    [7]="El fichero de configuración del DNS en Bind9 es /etc/bind/named.conf.options"
    [8]="El servicio que resuelve nombres a IP es el DNS"
    [9]="El puerto que usa el DNS es el 53"
    [10]="El DNS usa tanto protocolos TCP como UDP"
    [11]="El registro MX define el servidor de correo en el DNS"
    [12]="El registro NS define el servidor DNS autoritativo"
    [13]="El registro CNAME se usa para crear un alias en el DNS"
    [14]="El comando moderno para consultar el DNS es dig"
    [15]="La alternativa clásica a dig para consultas es nslookup"
    [16]="El directorio raíz de apache2 es /var/www/html"
    [17]="El fichero principal de configuración de apache2 es /etc/apache2/apache2.conf"
    [18]="El fichero de puertos a usar en apache2 es /etc/apache2/ports.conf"
    [19]="Los sitios virtuales disponibles en apache2 están en /etc/apache2/sites-available"
    [20]="Los sitios virtuales habilitados en apache2 están en /etc/apache2/sites-enabled"
    [21]="El fichero de configuración por defecto de apache2 es /etc/apache2/sites-available/000-default.conf"
    [22]="El puerto que usa HTTP es el 80"
    [23]="El puerto que usa HTTPS es el 443"
    [24]="El comando de Docker para instalar una imagen es docker pull"
    [25]="El comando de Docker para listar contenedores en ejecución es docker ps"
    [26]="El comando de Docker para parar un contenedor es docker stop"
    [27]="El comando de Docker para iniciar un contenedor es docker start"
    [28]="El comando de Docker para listar todos los contenedores es docker ps -a"
    [29]="El comando de Docker para listar redes es docker network ls"
    [30]="Un Docker sí permite la escalabilidad de las aplicaciones"
    [31]="El nombre del servicio FTP en Linux es vsftpd"
    [32]="La versión segura de FTP se llama SFTP"
    [33]="El protocolo para enviar emails es SMTP"
    [34]="El protocolo para recibir emails en su versión 3 es POP3"
    [35]="El usuario anónimo de FTP se llama anonymous"
    [36]="El puerto para acceder al servidor FTP es el 21"
    [37]="El puerto de datos FTP en modo activo es el 20"
    [38]="El protocolo FTP requiere numéricamente de 2 puertos"
    [39]="El protocolo seguro para copiar archivos remotamente es SCP"
    [40]="El comando de conexión remota que es seguro es SSH"
    [41]="El comando de conexión remota que no es seguro es Telnet"
    [42]="El comando de Linux que permite des/cifrar archivos es GPG"
    [43]="En SSH sí se suele usar el reenvío de puertos"
    [44]="Existen numéricamente 2 versiones de SSH"
    [45]="La versión de SSH más segura es la SSHv2"
    [46]="El puerto que usa SSH es el 22"
    [47]="El archivo de configuración del servidor SSH es /etc/ssh/sshd_config"
    [48]="El comando para generar claves SSH es ssh-keygen"
    [49]="La abreviatura del home personal de tu usuario es la virgulilla ~"
    [50]="El directorio de configuraciones generales del sistema es /etc"
    [51]="El directorio de logs generales de Linux es /var/log"
    [52]="Los dominios TLD cuelgan directamente del nodo raíz y los gestiona la ICANN"
    [53]="El organismo NIC administra dominios geográficos y asigna IPs únicas"
    [54]="La IANA es la parte de la ICANN que autoriza los TLD"
)

keys=("${!notas[@]}")
random_key=${keys[$RANDOM % ${#keys[@]}]}
echo -e "\n\e[44;97m${notas[$random_key]}\e[0m\n"

echo -e "\n\e[1;33mzzz\e[0m\n"